version: '3.7'

#networks:
#  docker01:
#    external: false


services:
  node-exporter:
    image: prom/node-exporter:latest
    network_mode: 'host'
    container_name: node-exporter1
    restart: unless-stopped
    ports:
      - '9108:9108'
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    volumes:
      - /proc:/host/proc
      - /sys:/host/sys
      - /:/rootfs
#    networks:
#      - docker01

  cadvisor:
    image: google/cadvisor:latest
    network_mode: 'host'
    container_name: cadvisor1
    restart: unless-stopped
    ports:
      - '8088:8088'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

#    networks:
#     - docker01
